import Head from "next/head";
import { Inter } from "next/font/google";
import { RxDashboard } from "react-icons/rx";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

interface Authenticated {
	children: JSX.Element;
}

export default function Authenticated({ children }: Authenticated) {
	function Sidebar(): JSX.Element {
		return (
			<div className="flex flex-col w-16 p-2 bg-gray-100 dark:bg-gray-800 gap-1 items-center rounded-xl">
				<div className="border-b w-fit flex flex-col justify-center py-2">
					<button className="flex justify-center items-center rounded-md h-8 w-8 hover:scale-105 transition">
						<RxDashboard size={26} color="rgb(99 102 241)" />
					</button>
				</div>
				<div className="w-fit flex gap-4 flex-col justify-center py-8">
					<button className="flex flex-col justify-center items-center rounded-md h-8 w-8 hover:scale-105 hover:bg-gray-200 transition">
						<RxDashboard size={18} color="rgb(99 102 241)" />
					</button>
					<button className="flex flex-col justify-center items-center rounded-md h-8 w-8 hover:scale-105 hover:bg-gray-200 transition">
						<RxDashboard size={18} color="rgb(99 102 241)" />
					</button>
				</div>
				<div className="w-fit border-t mt-auto flex flex-col justify-center py-2">
					<button className="flex flex-col justify-center items-center rounded-md h-8 w-8 hover:scale-105 hover:bg-gray-200 transition">
						<RxDashboard size={18} color="rgb(99 102 241)" />
					</button>
				</div>
			</div>
		);
	}
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col h-screen">
				<Header />
				<div className="flex mx-auto mt-4 w-full h-full max-w-[1920px] overflow-auto">
					<div className="h-full p-2 flex">
						<Sidebar />
					</div>
					<div className="p-2 w-full h-full flex overflow-auto">{children}</div>
				</div>
			</main>
		</>
	);
}
